name = input("Name: ")
last_name = input("Last name: ")
phone_number = input("Phone Number: ")
street = input("Street: ")
street_number = input("Street Number: ")
appartment_number = input("Appartment Number: ")
city = input("City: ")
post_code = input("Post code: ")
country = input("Country: ")

print(name + " " + last_name)
print(phone_number)
print("Str. " + street + " " + street_number + " ap. " + appartment_number + " " + city)
print(post_code)
print(country)

